"""fr this time

Revision ID: 32778e2f404c
Revises: 9b60b1f6a726
Create Date: 2026-03-13 17:45:33.339955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32778e2f404c'
down_revision: Union[str, None] = '9b60b1f6a726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worksheets_identifier'), table_name='worksheets')
    op.drop_column('worksheets', 'identifier')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worksheets', sa.Column('identifier', sa.VARCHAR(), nullable=False))
    op.create_index(op.f('ix_worksheets_identifier'), 'worksheets', ['identifier'], unique=1)
    # ### end Alembic commands ###
